### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by KleoPetroff** [KleoPetroff/jana-framework#1]
- [x] Responsive Grid System
- [x] Buttons
- [x] Forms and inputs
- [x] Typography
- [x] Tables
- [ ] Navigation and menus
- [ ] Javascript Modules

Ideas:
- [ ] Various Mixins
